### ISSUE TITLE
Show/hide hint button

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/course-website#10]
Execises will be written in StackEdit, where it should be possible write something similar to:

```Markdown
####### begin:hint
This is a hint that is only visible when the button have been pressed.

   ####### begin:hint
   This is a level 2 hint

     ####### begin:hint
     This is a level 3 hint
     ####### end:hint

  ####### end:hint
####### end:hint
```
It is perfectly fine to just toggle HTML visibilty of the ID tag. It is no problem that the student can View Source and see the hint in the html.

**Comment by iainbryson** [comment]
This should already work, does it not?

**Comment by iainbryson** [comment]
Ah. Looks like a bug I introduced when optimizing the Dockerfile.  Easy to fix.  I’ll fix it with today’s deployment unless you need it right now.

**Comment by dtu-compute** [comment]
No problem. I'll test after today's deployment =)

**Comment by dtu-compute** [comment]
I have now added a hint and result on the front page.

https://01005-staging.compute.dtu.dk/home

and they doesn't get parsed.

**Comment by iainbryson** [comment]
Ah, then I misunderstood : right not the design is only to parse Exercise* for the special directives.  It should be easy to expand that to all .md files if you want.  Did you manage to see it in action for exercises at least?

e.g.  https://01005-staging.compute.dtu.dk/exercise/Exercise-Test2

**Comment by dtu-compute** [comment]
It would be great if it could be for all md pages, as they might want to call their exercises different file names from course to course. Is that a problem?

Very nice! Can you centre the button on its own line? Right now it can appear at end of line.

**Comment by iainbryson** [comment]
It should be possible, but it’ll require some reworking.  Maybe this would
be better as a separate issue?  I can keep the centering as this issue.

**Comment by dtu-compute** [comment]
Excellent. Let's keep the current behavior where hints/results are parsed for Exercises*.

Center and newline the hint/result buttons for this ticket would be great.
