### ISSUE TITLE
Show/hide result button

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/course-website#11]
Exercises will be written in StackEdit, where it should be possible write something similar to:

```Markdown
####### begin:result
This is the solution to an exercises that is only visible when the button have been pressed.
####### end:result
```
It is perfectly fine to just toggle HTML visibility of the ID tag. It is no problem that the student can View Source and see the hint in the html.

**Comment by iainbryson** [comment]
This should already work, does it not?

**Comment by iainbryson** [comment]
Ah, no. Hint is done.

How is this functionally different from the hint?  It seems very similar...

**Comment by dtu-compute** [comment]
It is a last minute feature request which is exactly the same as the one for hints.
