### ISSUE TITLE
Admin page tabs. (was Error logs)

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/course-website#12]
Maybe already implemented?

The admin should have a `Show error logs` button, where parsing errors are shown from if-conditions and show/hide.

**Comment by iainbryson** [comment]
I can turn it into a button.  Right now the errors are just shown in the admin, but I suppose it makes more have this as a button and a modal when we move the file manager components into the admin page.

**Comment by dtu-compute** [comment]
Would it be possible to have tabs like these in the admin page?

* The first example at http://getbootstrap.com/components/#nav-justified
* http://getbootstrap.com/javascript/#tabs-examples

then there could be tabs for:

* StackEdit (containing the current button and error reporting)
* ShareLatex (just a "Get updates" button)
* File Manager

Would that be possible?
