### ISSUE TITLE
Needs to look nice on smaller monitors

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/course-website#13]
Right now the front page have some issues when make the screen horizontal smaller. See screenshot. I would have expected it would fall back to single column mode on smaller screens than it does. Or does that depend on the StackEdit content in the right column? E.g. tables and equations?

There is an issue with login name and login/logout.

![1](https://cloud.githubusercontent.com/assets/13518486/17294434/2055800a-57f7-11e6-8d56-8a65062187a2.png)

**Comment by iainbryson** [comment]
Seems much better now:

![image](https://cloud.githubusercontent.com/assets/1531103/17437744/80c8d114-5aed-11e6-93e3-68a09c094b8f.png)

**Comment by iainbryson** [comment]
Do you want to go further and make it work for tiny/mobile screens?

**Comment by dtu-compute** [comment]
No, desktop would be perfect.
