### ISSUE TITLE
Left column changes

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/course-website#16]
to perhaps the two gray colours used in menu.

**Comment by dtu-compute** [comment]
Instead of having the hard coded table, could this be removed, so whatever is written in Frontpage-left gets into left column? That way they can "StackEdit style" it they way they like.

**Comment by iainbryson** [comment]
It should already work like that.  There is some static content:

```
      <div id="left-rail" class=" col-lg-3"><!--*** left Section*****-->
        <div class="panel panel-default">
        <div class="panel-heading">Nyheder</div>
        <div class="panel-body"></div>
        </div>
```

But everything in “panel-body” gets replaced with the stack edit pieces.  I can remove the title if that’s what you want.  Good?

**Comment by dtu-compute** [comment]
Yes, exactly =)

**Comment by dtu-compute** [comment]
Better also remove the 1px border...
