### ISSUE TITLE
Latex is very small

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/course-website#20]
Both inline and `$$` are smaller on the website than in StackEdit.

![1](https://cloud.githubusercontent.com/assets/13518486/17372387/f27b91ac-59a3-11e6-91d9-0e11025a8e76.png)

**Comment by iainbryson** [comment]
Can you provide the markup for the function you're seeing the issues with?  I think I know the problem.

**Comment by dtu-compute** [comment]
It looks like this one got closed by a mistake based on the commit.

Latex is still very small in Firefox. This is what I used

```
You can render *LaTeX* mathematical expressions using **MathJax**, as on [math.stackexchange.com][1]:

The *Gamma function* satisfying $\Gamma(n) = (n-1)!\quad\forall n\in\mathbb N$ is via the Euler integral

$$
\Gamma(z) = \int_0^\infty t^{z-1}e^{-t}dt\,.
$$

> **Tip:** To make sure mathematical expressions are rendered properly on your website, include **MathJax** into your template:
```

**Comment by iainbryson** [comment]
I think it looks much better:

![image](https://cloud.githubusercontent.com/assets/1531103/17539598/5b144db6-5e7d-11e6-913a-45689cb02ff8.png)

Is that close enough?

**Comment by dtu-compute** [comment]
Perfect =)
