### ISSUE TITLE
Infinite login loop

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/course-website#27]
When I visit 01005-staging.compute.dtu.dk in Private browser mode in Firefox it changes to

https://auth.dtu.dk/dtu/login?service=https%3A%2F%2F01005-staging.compute.dtu.dk%2Fhome%2Findex&gateway=true&renew=1&redirection_loop_intercepted=1

and does an infinite login loop where it keeps reloading the page before it can render it. The front page shouldn't even need auth, so very strange.

**Comment by iainbryson** [comment]
Good catch!

I’ll need to research how to fix this.  The gateway redirect is supposed to allow the app to get the CAS creds even when the page does not require them. But it looks like it’s not working as expected in the case of not being logged in.
