### ISSUE TITLE
Move course name and login name a bit up

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/course-website#30]
When hovering the Logout button it covers the login name a bit.

![1](https://cloud.githubusercontent.com/assets/13518486/17524572/882f8644-5e5f-11e6-91bf-2115b73a47e4.png)

**Comment by iainbryson** [comment]
I can move the name up again, but then it will not be close to the login button — wasn’t there an issue about that?  I thought you preferred to have it closer.

**Comment by dtu-compute** [comment]
You are right. Hmm. Something strange must have happened somewhere. I proposed moving it down to align it with the course title.

Can you move both up so it doesn't overlap and still leaves a bit of space between login name and hovered Logout? =)

**Comment by dtu-compute** [comment]
Can we move them another 8px up? =)
