### ISSUE TITLE
Remove description in podcasts

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/course-website#32]
I assume that it is called "description" in the json key.

**Comment by dtu-compute** [comment]
It is still there it looks like.

**Comment by iainbryson** [comment]
It’s gone now.  Hmm.  Do you mean the description of each podcast, or the single course description at the top?

**Comment by dtu-compute** [comment]
It is the course description I was talking about. If another description have been removed, then it should be added again =)
