### ISSUE TITLE
Get course title from courses.yaml

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/course-website#41]
instead of from docker-compose.

**Comment by iainbryson** [comment]
If you mean COURSE_NAME in docker compose, the problem this solves is not so much the name displayed to the user as the which course's configuration to use for that particular instance of the container.  I'm not sure there's a more elegant way of doing it; we could try and parse it out of the url, but that seems a little hacky and requires a request for the container to now its (exernal) name.

But I think what you want is that in the header, the course title, which is currently, say 01005 to be changed to whatever .name is for course 01005 in courses.yaml.  Is that correct?

**Comment by dtu-compute** [comment]
Ok, I see.

Could it be renamed to `COURSE_ENV`?

> But I think what you want is that in the header, the course title, which is currently, say 01005 to be changed to whatever .name is for course 01005 in courses.yaml. Is that correct?

Exactly =)
