### ISSUE TITLE
begin/end question

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/course-website#49]

**Comment by iainbryson** [comment]
I assume this means "add begin/end:question" with similar semantics as answer and hint.

**Comment by dtu-compute** [comment]
It is a note to self, as I need to figure out how questions should be styled =) I

**Comment by iainbryson** [comment]
Do you want me to implement the functionality — as an extension of the existing feature?  Then we can add style later; that should be an orthogonal procedure.

**Comment by dtu-compute** [comment]
I am 99% sure the style should be a background colour of `#f0f0f0` which I took from the code block bg colour. So if that can be implemented, then let's do that. =)
