### ISSUE TITLE
Two column frontpage

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/course-website#6]
Two columns where one is for News (25% text width) and the other for Welcome text.

The news items could e.g. be written in StackEdit as (but think of it as random Markdown)

```
# 12/01-2016 New quizzes now available
You can now test your skills on this weeks material by taking the latest quizzes on the Quiz website.

# 10/01-2016 Older news
Some older news here
```

I propose that the Frontpage is a join of two StackEdit pages. Good idea/bad idea code wise?

**Comment by iainbryson** [comment]
Is this not already what you see?

**Comment by dtu-compute** [comment]
Yes.

**Comment by dtu-compute** [comment]
Reopening as the two columns should only be for the front page.

**Comment by iainbryson** [comment]
Should be fixes with today's changes.
