### ISSUE TITLE
if-condition parser

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/course-website#9]
Maybe the following is already implemented?

Needs to be server side.

Some content should require login and for the student to be member of a certain class. So we need some sort of syntax similar to this:

```Markdown
####### begin:only A, B, biotek1
Here is content that only students in the classes `A, B, biotek1` can see.
####### end:only
```

This will e.g. be used on the Information page of the site, where the students will only see the course schedule for the class they belong to. So it should be possible to have multiple of these if-conditions on the page.

**Comment by iainbryson** [comment]
This should already work.
